language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk: oraclejdk8

after_success:
 - echo "<settings><servers><server><id>snapshots</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server><server><id>release</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
 - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == OTBProject/OTBProject ]] && ( [[ $TRAVIS_BRANCH == master ]] || [[ $TRAVIS_BRANCH == dev ]] ) && mvn deploy --settings ~/settings.xml"


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2e240a1b47dca719855d
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
