language: java
jdk: oraclejdk8
install: mvn clean install
after-success:
 - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == OTBPoject/OTBProject ]] && [[ $TRAVIS_BRANCH == master ]] && mvn deploy"
